// AWS Amplify Configuration
// These values are pulled from aws-exports.js (auto-generated by Amplify)
// This file is kept as a reference / backup

const awsConfig = {
  Auth: {
    Cognito: {
      userPoolId: 'us-east-1_XVaCROxT4',
      userPoolClientId: '5kbjuce29borckbm1slqcp7dpr',
      identityPoolId: 'us-east-1:f5a3e30b-4dde-4913-8e38-666f0e78600c',
      loginWith: {
        email: true,
      },
      signUpVerificationMethod: 'code',
      userAttributes: {
        email: {
          required: true,
        },
      },
    },
  },
  Storage: {
    S3: {
      bucket: 'blackdropboxfilesda4d9-dev',
      region: 'us-east-1',
    },
  },
  API: {
    REST: {
      blackdropboxapi: {
        endpoint: 'https://2g65909p33.execute-api.us-east-1.amazonaws.com/dev',
        region: 'us-east-1',
      },
    },
  },
};

export default awsConfig;
